name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker Images
        run: docker-compose build

      - name: Start Services
        run: docker-compose up -d

      - name: Run Tests in Docker
        run: docker ps

      - name: Verify API Endpoints
        run: |
          curl http://localhost:5000/api/transactions
          curl http://localhost:5000/api/customers
          curl http://localhost:5000/api/externalData

      - name: Run Tests in hive
        run: docker exec -it hive bash -c "hive -e 'show tables;'"